services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: cashflow-fe
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
